apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: oauth-custom
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  identityProviders:
    - name: COE_LDAP
      mappingMethod: claim
      type: LDAP
      ldap:
        attributes:
          email: []
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: 'uid=mmaiti,cn=users,cn=accounts,dc=coe,dc=muc,dc=redhat,dc=com'
        bindPassword:
          name: ldap-secret
        insecure: true
        url: >-
          ldap://inf96.coe.muc.redhat.com/cn=users,cn=accounts,dc=coe,dc=muc,dc=redhat,dc=com?uid
