apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesJson6902:
- target:
    version: v1
    kind: Group
    group: user.openshift.io
    name: clusteradmins
  path: clusteradmins-group-users.yaml