apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '11'
  name: config-groups
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: config
  source:
    path: components/configs/groups
    repoURL: https://github.com/mannyci/ocp-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true